name: Pull Request Check

on:
  schedule:
    - cron: '30 8 * * *'    # Her gün sabah 11:30 (TR) çalıştır. (UTC saat dilimi)
  push:
    branches: [ "master" ]
  pull_request:
    types:
      - approved
    branches:
        - master
  workflow_dispatch:    # manuel çalıştırma butonunu aktive eder

jobs:
  check-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: "Install Packages"
        run: "mvn install -DskipTests"

      - name: Run Tests
        continue-on-error: true    #  hatanın görmezden gelinmesi için eklendi
        run: |
          mvn clean
          mvn test

      - name: Rapor dosyalarını kaydet
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            target/cucumber-html-reports
            target/reports/html/html_reports.html
            target/PdfReport/ExtentPdf.pdf

          
          
